#!/bin/bash
#

siteroot="/home/i/ixrevo/reasonguide.ru/public_html"

while read oldrev newrev ref
do
  branch=`echo $ref | cut -d/ -f3`

  if [ "master" == "$branch" ]; then
    git archive master | tar -x -C $siteroot
  fi
done